### PR TITLE
Upgrade TSTyche

### PR DESCRIPTION
**Pull request by mrazauskas**
TSTyche 2 is available as a release candidate, see: https://tstyche.org/releases/tstyche-2

There are two mayor improvements: matchers got better names and minimal `--watch` was added. At the moment it watches on the test files and TSTyche config file. That’s good for beginning. I made the changes you see in this PR while running TSTyche in the watch mode and that went quick and smooth.

@FloEdelmann You were interested to try out the watch mode (https://github.com/FloEdelmann/vue-ts-types/issues/506#issuecomment-1961045741). Give it a spin (;

The plan is to release stable version in a week or so. It is fine to wait and to land this PR later. Just wanted to drop you a note that `--watch` is already implemented.

### CODE REVIEW

**Review by FloEdelmann — APPROVED** [review]
Wow, thank you for notifying me and also already migrating this repo to the new version!

The changes look good. I also tried out the watch mode and it works well.

I think I'll already merge this, given that this is already the second release candidate and you plan to release the stable version next week, so no major changes are to be expected.

**Comment by mrazauskas** [comment]
Thanks for quick response!

I was migrating few repos (including yours) to see, if any bugs could be found. One detail got caught and fixed. Otherwise the `rc` is stable and ready for general use.

**Comment by FloEdelmann** [comment]
Only minor annoyance with the watch mode: Jest's watch mode trained my muscle memory to press <kbd>q</kbd> for quitting instead of <kbd>x</kbd> for exiting. Maybe that can be added as an (invisible?) alias?

**Comment by mrazauskas** [comment]
Yes, it makes sense to add `q` as an alias. There are few already. Exit works on: `escape`, `cmd+c`, `cmd+d`, `x` and `X`. And rerun all works with: `space`, `enter`, `a` and `A`.

That’s too noisy to document in the terminal. I will add a line to docs. And will add `q` and `Q` aliases too. Thanks for the idea.

**Pull request merged**
